default_language_version:
  # force all unspecified python hooks to run python3.8
  python: python3.8
repos:
  # General pre-commits
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
        description: "Check accidental private keys in code"
      - id: requirements-txt-fixer
        description: "Sort requirements alphabetically"
      - id: trailing-whitespace
        description: "Remove trailing whitespaces"
  # For python files
  - repo: https://github.com/psf/black
    # Code style
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Fast linter to replace flake8 
    rev: 'v0.0.209'
    hooks:
     - id: ruff
       fail_fast: true
  - repo: https://github.com/pycqa/isort
    # Sort imports and adds section names
    rev: 5.11.4
    hooks:
      - id: isort
        description: "Sort python imports and add sections titles as single line comment (setup in pyproject.toml)"
  # Same tools but for Jupyter notebooks
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.0
    hooks:
      - id: nbqa-black
        name: nbqa-black
        description: "Run 'black' on a Jupyter Notebook"
        language: python
        require_serial: true
      - id: nbqa-ruff
        name: nbqa-ruff
        description: "Run ruff on a Jupyter notebook"
        fail_fast: true
      - id: nbqa-isort

            

  